"""add memory table

Revision ID: 3f361632e1b7
Revises: a0b0b76bec6b
Create Date: 2026-03-16 14:12:35.347188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f361632e1b7'
down_revision: Union[str, Sequence[str], None] = 'a0b0b76bec6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Memory', sa.Column('createdAt', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Memory', 'createdAt')
    # ### end Alembic commands ###
