"""Add cascade delete to foreign keys

Revision ID: a0b0b76bec6b
Revises: bd5b410d3ddf
Create Date: 2026-03-11 16:34:47.022057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0b0b76bec6b'
down_revision: Union[str, Sequence[str], None] = 'bd5b410d3ddf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Chat', 'userId',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('Chat_userId_fkey'), 'Chat', type_='foreignkey')
    op.create_foreign_key(None, 'Chat', 'User', ['userId'], ['id'], ondelete='CASCADE')
    op.alter_column('Message', 'chatId',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('Message_chatId_fkey'), 'Message', type_='foreignkey')
    op.create_foreign_key(None, 'Message', 'Chat', ['chatId'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'Message', type_='foreignkey')
    op.create_foreign_key(op.f('Message_chatId_fkey'), 'Message', 'Chat', ['chatId'], ['id'])
    op.alter_column('Message', 'chatId',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'Chat', type_='foreignkey')
    op.create_foreign_key(op.f('Chat_userId_fkey'), 'Chat', 'User', ['userId'], ['id'])
    op.alter_column('Chat', 'userId',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
